### PR TITLE
more x64 support

### PR DESCRIPTION
**Pull request by gurikbal**
See [issue](https://github.com/pnedev/nppgtags/issues/26)

### CODE REVIEW

**Comment by pnedev** [comment]
Hi @gurikbal ,

This doesn't change anything as far as I can tell.
What is the reason behind this PR?

The referenced issue is resolved (https://github.com/pnedev/nppgtags/issues/26#issuecomment-515638062).

**Comment by gurikbal** [comment]
yes it's working but a version of Visual C++ Redistributable Packages should be installed rather this

**Comment by pnedev** [comment]
> a version of Visual C++ Redistributable Packages should be installed

Oh, I'll have to check that.
You mean NppGTags.dll is not statically linked to the run-time library?

This PR doesn't fix that anyway.

**Comment by gurikbal** [comment]
https://youtu.be/5VaEmb6F8pk

**Comment by gurikbal** [comment]
> This PR doesn't fix that anyway.

there release of qkNppReverseLines has also dependency of Visual C++ Redistributable but while i compile(vs 2012) it why dependency of Visual C++ Redistributable is gone without any code changes for x64
https://github.com/querykuma/qkNppReverseLines

**Comment by pnedev** [comment]
@gurikbal ,

Please check if the issue still persist in this build:
https://ci.appveyor.com/project/pnedev/nppgtags

x64 binary: https://ci.appveyor.com/api/buildjobs/4vooc2gnp5g1a3uy/artifacts/NppGTags.x64.Release.v141.dll

x86 binary: https://ci.appveyor.com/api/buildjobs/kwk72c1jaeatsk5n/artifacts/NppGTags.x86.Release.v141.dll

**Comment by gurikbal** [comment]
> @gurikbal ,
> 
> Please check if the issue still persist in this build:
> https://ci.appveyor.com/project/pnedev/nppgtags
> 
> x64 binary: https://ci.appveyor.com/api/buildjobs/4vooc2gnp5g1a3uy/artifacts/NppGTags.x64.Release.v141.dll
> 
> x86 binary: https://ci.appveyor.com/api/buildjobs/kwk72c1jaeatsk5n/artifacts/NppGTags.x86.Release.v141.dll

oh yes i was forget that. NppGTags.x64.Release.v141.dll and  NppGTags.x86.Release.v141.dll works 100% in win10 x64 

https://bruderste.in/octopress/ 
4. /MT everything.
https://bruderste.in/octopress/images/MTEverything.PNG

**Comment by gurikbal** [comment]
> This PR doesn't fix that anyway.

than compare using plugin API https://github.com/npp-plugins/plugintemplate/releases/tag/v3.1
that demo plugin work for me here.

**Comment by pnedev** [comment]
@gurikbal,

OK, thanks for testing and reporting that.

BR

**Comment by gurikbal** [comment]
i think problem(<RuntimeLibrary>MultiThreaded</RuntimeLibrary>) was in .vcxproj for x64
https://github.com/KubaDee/NppTextViz/pull/4

**Comment by pnedev** [comment]
@gurikbal ,

Does it have something to do with NppGTags?

**Comment by gurikbal** [comment]
i don't know but project of KubaDee both occur here in my win 10 my VS and appvyor

becuse it works after add `<RuntimeLibrary>MultiThreaded</RuntimeLibrary>` in .vcxproj
everywhere
https://github.com/KubaDee/NppTextViz/pull/4

**Pull request closed without merging**
